stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app1
      pushRemote: true
      registry: 127.0.0.1:34557
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app2
      pushRemote: true
      registry: 127.0.0.1:34557
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./2048_env.yaml
  - applyYamlConfig:
      path: ./2048_test.yaml
timeout: 60
notification: {}
